server:
      port: 8889

      logging:
        path: logs
        file: mylog.log


      spring:
        application:
          name: report
        datasource:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/test
          username: root
          password: 123456

      mybatis:
        #typeAliasesPackage扫描mybatis的实体类的位置，其实就是java-bean
        type-aliases-package: com.course.model
        #指定mybatis映射文件的地址（在resources下有个mapper文件夹，里面放的是sql的xml文件）
        mapper-locations:
        - mapper/*